"""fix_user_name_column_consolidation

Revision ID: 52376553099b
Revises: 20250622_entra_id
Create Date: 2025-06-22 11:50:29.876997

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from app.core.database import GUID

# revision identifiers, used by Alembic.
revision: str = "52376553099b"
down_revision: Union[str, None] = "20250622_entra_id"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("families", sa.Column("admin_user_id", GUID(), nullable=False))
    op.create_foreign_key(None, "families", "users", ["admin_user_id"], ["id"])
    op.add_column("family_members", sa.Column("accessibility_needs", sa.Text(), nullable=True))
    op.add_column("family_members", sa.Column("emergency_contact", sa.Text(), nullable=True))
    op.add_column("family_members", sa.Column("is_active", sa.Boolean(), nullable=True))
    op.alter_column(
        "family_members",
        "role",
        existing_type=sa.VARCHAR(length=8),
        type_=sa.Enum("COORDINATOR", "ADULT", "CHILD", name="familyrole"),
        existing_nullable=False,
    )
    op.drop_column("family_members", "special_needs")
    op.drop_column("family_members", "email")
    op.alter_column(
        "itinerary_activities",
        "google_place_id",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "reservations",
        "google_place_id",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "reservations",
        "duration_hours",
        existing_type=sa.INTEGER(),
        type_=sa.Numeric(precision=5, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "reservations",
        "cancellation_policy",
        existing_type=sa.VARCHAR(length=14),
        type_=sa.Enum(
            "FREE_CANCELLATION", "MODERATE", "STRICT", "NO_REFUND", name="cancellationpolicy"
        ),
        existing_nullable=True,
    )
    op.alter_column(
        "reservations",
        "external_provider",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=50),
        existing_nullable=True,
    )
    op.add_column("users", sa.Column("name", sa.String(length=255), nullable=True))
    op.add_column("users", sa.Column("picture", sa.Text(), nullable=True))
    op.add_column("users", sa.Column("is_verified", sa.Boolean(), nullable=True))
    op.alter_column("users", "auth0_id", existing_type=sa.VARCHAR(length=255), nullable=True)
    op.alter_column(
        "users",
        "role",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum(
            "SUPER_ADMIN", "FAMILY_ADMIN", "TRIP_ORGANIZER", "FAMILY_MEMBER", name="userrole"
        ),
        existing_nullable=False,
        existing_server_default=sa.text("'family_admin'"),
    )
    op.alter_column(
        "users",
        "phone",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=50),
        existing_nullable=True,
    )
    op.alter_column("users", "onboarding_completed", existing_type=sa.BOOLEAN(), nullable=True)
    op.drop_column("users", "date_of_birth")
    op.drop_column("users", "first_name")
    op.drop_column("users", "last_name")
    op.drop_column("users", "profile_picture_url")
    op.drop_column("users", "emergency_contact")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("emergency_contact", sa.TEXT(), nullable=True))
    op.add_column("users", sa.Column("profile_picture_url", sa.TEXT(), nullable=True))
    op.add_column("users", sa.Column("last_name", sa.VARCHAR(length=100), nullable=False))
    op.add_column("users", sa.Column("first_name", sa.VARCHAR(length=100), nullable=False))
    op.add_column("users", sa.Column("date_of_birth", sa.DATE(), nullable=True))
    op.alter_column("users", "onboarding_completed", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "users",
        "phone",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=20),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "role",
        existing_type=sa.Enum(
            "SUPER_ADMIN", "FAMILY_ADMIN", "TRIP_ORGANIZER", "FAMILY_MEMBER", name="userrole"
        ),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
        existing_server_default=sa.text("'family_admin'"),
    )
    op.alter_column("users", "auth0_id", existing_type=sa.VARCHAR(length=255), nullable=False)
    op.drop_column("users", "is_verified")
    op.drop_column("users", "picture")
    op.drop_column("users", "name")
    op.alter_column(
        "reservations",
        "external_provider",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "reservations",
        "cancellation_policy",
        existing_type=sa.Enum(
            "FREE_CANCELLATION", "MODERATE", "STRICT", "NO_REFUND", name="cancellationpolicy"
        ),
        type_=sa.VARCHAR(length=14),
        existing_nullable=True,
    )
    op.alter_column(
        "reservations",
        "duration_hours",
        existing_type=sa.Numeric(precision=5, scale=2),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "reservations",
        "google_place_id",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "itinerary_activities",
        "google_place_id",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.add_column("family_members", sa.Column("email", sa.VARCHAR(length=255), nullable=True))
    op.add_column("family_members", sa.Column("special_needs", sa.TEXT(), nullable=True))
    op.alter_column(
        "family_members",
        "role",
        existing_type=sa.Enum("COORDINATOR", "ADULT", "CHILD", name="familyrole"),
        type_=sa.VARCHAR(length=8),
        existing_nullable=False,
    )
    op.drop_column("family_members", "is_active")
    op.drop_column("family_members", "emergency_contact")
    op.drop_column("family_members", "accessibility_needs")
    op.drop_constraint(None, "families", type_="foreignkey")
    op.drop_column("families", "admin_user_id")
    # ### end Alembic commands ###
