[tool.importlinter]
root_packages = ["app"]

[[tool.importlinter.contracts]]
name = "Layered architecture for backend"
type = "layers"
layers = [
    "app.api",
    "app.services", 
    "app.core",
]

[[tool.importlinter.contracts]]
name = "Clean architecture enforcement"
type = "forbidden"
source_modules = ["app.api"]
forbidden_modules = ["app.core"]

[[tool.importlinter.contracts]]
name = "Service layer isolation"
type = "forbidden"
source_modules = ["app.services"]
forbidden_modules = ["app.api"] 