name: Simple Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy Infrastructure
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./infrastructure/bicep/main.bicep
          scope: resourcegroup
          parameters: |
            appName=pathfinder
            environment=dev
            sqlAdminLogin=${{ secrets.SQL_ADMIN_LOGIN }}
            sqlAdminPassword=${{ secrets.SQL_ADMIN_PASSWORD }}
            openAIApiKey=${{ secrets.OPENAI_API_KEY }}
      
      - name: Update Backend Configuration
        run: |
          az containerapp update \
            --name pathfinder-backend \
            --resource-group ${{ secrets.AZURE_RG }} \
            --set-env-vars \
              "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" \
              "ENVIRONMENT=production" \
              "DEBUG=false"
      
      - name: Restart Frontend
        run: |
          az containerapp revision restart \
            --name pathfinder-frontend \
            --resource-group ${{ secrets.AZURE_RG }}
      
      - name: Test Deployment
        run: |
          echo "Testing backend health..."
          curl -f https://pathfinder-backend.yellowdune-9b8d769a.eastus.azurecontainerapps.io/health
          echo "Testing frontend..."
          curl -f https://pathfinder-frontend.yellowdune-9b8d769a.eastus.azurecontainerapps.io/
          echo "✅ Deployment successful!" 